/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package caballos;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author diego
 */
public class Caballo extends javax.swing.JPanel implements Runnable {

    private int x = getWidth(); // Coordenada de origen x
    private int y = getHeight(); // Coordenada de origen y
    int contador = 1;
    private Image imagen;
    
    private String img1 = "C:\\Users\\diego\\OneDrive\\Documentos\\Ingenieria en Ciencias y Sistemas\\2023\\Segundo Semestre\\Laboratorio_IPC1_2S2023\\Clase 8\\Caballos\\src\\img\\caballo2.png";
    private String img2 = "C:\\Users\\diego\\OneDrive\\Documentos\\Ingenieria en Ciencias y Sistemas\\2023\\Segundo Semestre\\Laboratorio_IPC1_2S2023\\Clase 8\\Caballos\\src\\img\\caballo.png";
    Thread hilo;
    
    private int velocidad;

    public Caballo() {
        initComponents();
        hilo = new Thread(this);
        imagen = new ImageIcon(img1)
                       .getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT);
    }
    
    public void setVelocidad(int distancia) {
        Random random = new Random();
        velocidad = random.nextInt(distancia) + 1;
        
        velocidad *= 1000;
        texto.setText(distancia + "km");
    }
    
    public void mostrarVelocidad() {
        System.out.println("Velocidad: " + velocidad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto = new javax.swing.JLabel();

        texto.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto)
                .addContainerGap(278, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void paint(Graphics g) {
        g.setColor(getBackground());
        g.fillRect(0, 0, getWidth(), getWidth());
        g.drawImage(imagen, x, y, this);
    }

    public void inicio() {
        hilo.start();
    }

    @Override
    public void run() {
        try {
            
            boolean carrera = true;
            
            while (carrera) {
                
                if (contador == 1) carrera = false;
                
                if (x == 50) {
                    // Contador para cuando llegue a 0,0
                    contador++;
                }

                while (x <= getWidth() - 60) {
                    imagen = new ImageIcon(img1)
                                   .getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT);
                    // Velocidad de la animacion
                    Thread.sleep(velocidad);
                    
                    // Distancia del objeto a la derecha
                    x += 10;
                    repaint();
                }

                while (x > 10) {
                    imagen = new ImageIcon(img2)
                                   .getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT);
                    
                    Thread.sleep(velocidad);
                    
                    x -= 10;
                    repaint();
                }
                System.out.println(contador);
            }
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
